-- MySQL Script generated by MySQL Workbench
-- Fri Mar 10 16:27:01 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema padrao_documento
-- -----------------------------------------------------
-- Schema do Sistema para Descrição de Banco de Dados
DROP SCHEMA IF EXISTS `padrao_documento` ;

-- -----------------------------------------------------
-- Schema padrao_documento
--
-- Schema do Sistema para Descrição de Banco de Dados
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `padrao_documento` DEFAULT CHARACTER SET utf8 ;
USE `padrao_documento` ;

-- -----------------------------------------------------
-- Table `padrao_documento`.`T_SPDC_VOCB_CNTLD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `padrao_documento`.`T_SPDC_VOCB_CNTLD` ;

CREATE TABLE IF NOT EXISTS `padrao_documento`.`T_SPDC_VOCB_CNTLD` (
  `ID_VOCB_CNTLD` INT NOT NULL COMMENT 'Identificador unico da tabela de vocabularios controlados.',
  `SG_VOCB_CNTLD` VARCHAR(5) NOT NULL COMMENT 'Sigla do termo usado no vocabulário controlado',
  `DS_VOCB_CNTLD` VARCHAR(1000) NOT NULL COMMENT 'Descricao do termo usado no vocabulario controlado',
  PRIMARY KEY (`ID_VOCB_CNTLD`),
  INDEX `PK_VOCB_CONTLD` (`ID_VOCB_CNTLD` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `padrao_documento`.`T_SPDC_PRFX_OBJT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `padrao_documento`.`T_SPDC_PRFX_OBJT` ;

CREATE TABLE IF NOT EXISTS `padrao_documento`.`T_SPDC_PRFX_OBJT` (
  `ID_PRFX_OBJT` INT NOT NULL COMMENT 'Identificador unico do prefixo de objetos do banco. Por exemplo, DS para atributos usados como descricao, e T para tabelas.',
  `SG_PRFX_OBJT` VARCHAR(4) NOT NULL COMMENT 'Sigla do prefixo de objeto de banco.',
  `DS_PRFX_OBJT` VARCHAR(400) NOT NULL COMMENT 'Descricao do prefixo de objeto de banco..',
  `TP_PRFX_OBJT` VARCHAR(1) NOT NULL COMMENT 'Tipo de prefixo do objeto do banco de dados. T para Tabela. V para view. S para sequence. I para indice. A para atributo. P para primary key. F para foreign key. U para unique key. C para check.',
  `DS_TIPO_DADO_PRFX` VARCHAR(50) NOT NULL COMMENT 'Descricao do tipo de dado usado para o prefixo.',
  `DS_CNTD_TIPO_DADO_PRFX` VARCHAR(50) NOT NULL COMMENT 'Descricao do conteudo do tipo de dado do prefixo.',
  `DS_EXPLO_PRFX_OBJT` VARCHAR(50) NOT NULL COMMENT 'Descricao do exemplo do prefixo',
  `DS_DFNC_PRFX_OBJT` VARCHAR(400) NOT NULL COMMENT 'Descricao ampla da definicao do prefixo de objeto.',
  PRIMARY KEY (`ID_PRFX_OBJT`),
  INDEX `PK_PRFX_OBJJT` (`ID_PRFX_OBJT` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `padrao_documento`.`T_SPDC_OBJT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `padrao_documento`.`T_SPDC_OBJT` ;

CREATE TABLE IF NOT EXISTS `padrao_documento`.`T_SPDC_OBJT` (
  `ID_OBJT` INT NOT NULL COMMENT 'Identificador único do objeto inserido no sistema de padronizao de documentos.',
  `NM_OBJT` VARCHAR(50) NOT NULL COMMENT 'Nome do objeto de padronizacao de documentos.',
  `TP_OBJT` VARCHAR(2) NOT NULL COMMENT 'Tipo do objeto para padronizacao de documetos. BD para documentos de banco de dados, por exemplo, scripts. DC para demais documentos.',
  `DC_OBJT` VARCHAR(1000) NULL COMMENT 'Descricao a respeito do objeto.',
  PRIMARY KEY (`ID_OBJT`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `padrao_documento`.`T_SPDC_OBJT_VOCB_CNTLD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `padrao_documento`.`T_SPDC_OBJT_VOCB_CNTLD` ;

CREATE TABLE IF NOT EXISTS `padrao_documento`.`T_SPDC_OBJT_VOCB_CNTLD` (
  `ID_OBJT` INT NOT NULL COMMENT 'Identificador único do objeto inserido no sistema de padronizao de documentos.',
  `ID_VOCB_CNTLD` INT NOT NULL COMMENT 'Identificador unico da tabela de vocabularios controlados.',
  INDEX `IX_SPDC_VOCB_CNTLD` (`ID_VOCB_CNTLD` ASC),
  INDEX `IX_SPDC_OBJT_VOCB_CNTLD` (`ID_OBJT` ASC),
  PRIMARY KEY (`ID_OBJT`, `ID_VOCB_CNTLD`),
  CONSTRAINT `FK_SPDC_OBJT_VOCB_CNTLD`
    FOREIGN KEY (`ID_OBJT`)
    REFERENCES `padrao_documento`.`T_SPDC_OBJT` (`ID_OBJT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_SPDC_VOCB_CNTLD`
    FOREIGN KEY (`ID_VOCB_CNTLD`)
    REFERENCES `padrao_documento`.`T_SPDC_VOCB_CNTLD` (`ID_VOCB_CNTLD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `padrao_documento`.`T_SPDC_OBJT_PRFX`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `padrao_documento`.`T_SPDC_OBJT_PRFX` ;

CREATE TABLE IF NOT EXISTS `padrao_documento`.`T_SPDC_OBJT_PRFX` (
  `ID_OBJT` INT NOT NULL COMMENT 'Identificador único do objeto inserido no sistema de padronizao de documentos.',
  `ID_PRFX_OBJT` INT NOT NULL COMMENT 'Identificador unico do prefixo de objetos do banco. Por exemplo, DS para atributos usados como descricao, e T para tabelas.',
  INDEX `IX_SPDC_OBJT_PRFX` (`ID_OBJT` ASC),
  INDEX `IX_SPDC_PRFX_OBJT` (`ID_PRFX_OBJT` ASC),
  PRIMARY KEY (`ID_OBJT`, `ID_PRFX_OBJT`),
  CONSTRAINT `FK_SPDC_OBJT_PRFX_01`
    FOREIGN KEY (`ID_OBJT`)
    REFERENCES `padrao_documento`.`T_SPDC_OBJT` (`ID_OBJT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_SPDC_PRFX_OBJT_02`
    FOREIGN KEY (`ID_PRFX_OBJT`)
    REFERENCES `padrao_documento`.`T_SPDC_PRFX_OBJT` (`ID_PRFX_OBJT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `padrao_documento`.`T_SPDC_PRPD_OBJT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `padrao_documento`.`T_SPDC_PRPD_OBJT` ;

CREATE TABLE IF NOT EXISTS `padrao_documento`.`T_SPDC_PRPD_OBJT` (
  `ID_PRPD_OBJT` INT NOT NULL COMMENT 'Identificador unico das propriedades de um objeto.',
  `ID_OBJT` INT NOT NULL COMMENT 'Identificador único do objeto inserido no sistema de padronizao de documentos.',
  `NM_PRPD_OBJT` VARCHAR(50) NOT NULL,
  `DC_PRPD_OBJT` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`ID_PRPD_OBJT`),
  INDEX `IX_SPDC_OBJT_PRPD` (`ID_OBJT` ASC),
  CONSTRAINT `FK_SPDC_OBJT_PRPD01`
    FOREIGN KEY (`ID_OBJT`)
    REFERENCES `padrao_documento`.`T_SPDC_OBJT` (`ID_OBJT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `padrao_documento`.`T_SPDC_PRPD_VOCB_CNTLD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `padrao_documento`.`T_SPDC_PRPD_VOCB_CNTLD` ;

CREATE TABLE IF NOT EXISTS `padrao_documento`.`T_SPDC_PRPD_VOCB_CNTLD` (
  `ID_PRPD_OBJT` INT NOT NULL COMMENT 'Identificador unico das propriedades de um objeto.',
  `ID_VOCB_CNTLD` INT NOT NULL COMMENT 'Identificador unico da tabela de vocabularios controlados.',
  PRIMARY KEY (`ID_PRPD_OBJT`, `ID_VOCB_CNTLD`),
  INDEX `IX_SPDC_PRPD_VOCB_CNTLD` (`ID_VOCB_CNTLD` ASC),
  CONSTRAINT `FK_SPDC_PRPD_VOCB_CNTLD01`
    FOREIGN KEY (`ID_VOCB_CNTLD`)
    REFERENCES `padrao_documento`.`T_SPDC_VOCB_CNTLD` (`ID_VOCB_CNTLD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_SPDC_PRPD_VOCB_CNTLD02`
    FOREIGN KEY (`ID_PRPD_OBJT`)
    REFERENCES `padrao_documento`.`T_SPDC_PRPD_OBJT` (`ID_PRPD_OBJT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `padrao_documento`.`T_SPDC_PRPD_OBJT_PRFX`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `padrao_documento`.`T_SPDC_PRPD_OBJT_PRFX` ;

CREATE TABLE IF NOT EXISTS `padrao_documento`.`T_SPDC_PRPD_OBJT_PRFX` (
  `ID_PRPD_OBJT` INT NOT NULL COMMENT 'Identificador unico das propriedades de um objeto.',
  `ID_PRFX_OBJT` INT NOT NULL COMMENT 'Identificador unico do prefixo de objetos do banco. Por exemplo, DS para atributos usados como descricao, e T para tabelas.',
  PRIMARY KEY (`ID_PRPD_OBJT`, `ID_PRFX_OBJT`),
  INDEX `IX_SPDC_PRPD_PRFX` (`ID_PRFX_OBJT` ASC),
  CONSTRAINT `FK_SPDC_PRPD_OBJT01`
    FOREIGN KEY (`ID_PRPD_OBJT`)
    REFERENCES `padrao_documento`.`T_SPDC_PRPD_OBJT` (`ID_PRPD_OBJT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_SPDC_PRPD_PRFX02`
    FOREIGN KEY (`ID_PRFX_OBJT`)
    REFERENCES `padrao_documento`.`T_SPDC_PRFX_OBJT` (`ID_PRFX_OBJT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
