-- MySQL Script generated by MySQL Workbench
-- Thu Jun  8 08:39:32 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema padrao_documento
-- -----------------------------------------------------
-- Schema do Sistema para Descrição de Banco de Dados
DROP SCHEMA IF EXISTS `padrao_documento` ;

-- -----------------------------------------------------
-- Schema padrao_documento
--
-- Schema do Sistema para Descrição de Banco de Dados
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `padrao_documento` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `padrao_documento` ;

-- -----------------------------------------------------
-- Table `padrao_documento`.`T_SPDC_VOCB_CNTLD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `padrao_documento`.`T_SPDC_VOCB_CNTLD` ;T_SPDC_OBJT

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `padrao_documento`.`T_SPDC_VOCB_CNTLD` (
  `ID_VOCB_CNTLD` INT NOT NULL COMMENT '',
  `SG_VOCB_CNTLD` VARCHAR(10) NOT NULL COMMENT 'Sigla do termo usado no vocabulário controlado',
  `DS_VOCB_CNTLD` VARCHAR(1000) NOT NULL COMMENT 'Descricao do termo usado no vocabulario controlado',
  `FL_TIPO_VOCB_CNTLD` VARCHAR(1) NULL COMMENT 'Flag do tipo de vocabulario controlado usado para compor nomes de objetos e suas propriedades.',
  PRIMARY KEY (`ID_VOCB_CNTLD`));
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `PK_VOCB_CONTLD` ON `padrao_documento`.`T_SPDC_VOCB_CNTLD` (`ID_VOCB_CNTLD` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `padrao_documento`.`T_SPDC_PRFX`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `padrao_documento`.`T_SPDC_PRFX` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `padrao_documento`.`T_SPDC_PRFX` (
  `ID_PRFX` INT NOT NULL COMMENT 'Identificador unico do prefixo de objetos do banco. Por exemplo DS para atributos usados como descricao e T para tabelas.',
  `SG_PRFX` VARCHAR(4) NOT NULL COMMENT 'Sigla do prefixo de objeto de banco.',
  `DS_TIPO_DADO_PRFX` VARCHAR(400) NOT NULL COMMENT 'Descricao do tipo de dado do prefixo de objeto',
  `DS_CNTD_PRFX` VARCHAR(400) NOT NULL COMMENT 'Descricao do conteudo do prefixo de objeto',
  `DS_EXPLO_PRFX` VARCHAR(400) NOT NULL COMMENT 'Descricao do exemplo do prefixo',
  `DS_DFNC_PRFX` VARCHAR(400) NOT NULL COMMENT 'Descricao ampla da definicao do prefixo de objeto.',
  PRIMARY KEY (`ID_PRFX`));
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `PK_PRFX_OBJT` ON `padrao_documento`.`T_SPDC_PRFX` (`ID_PRFX` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `padrao_documento`.`T_TIPO_OBJT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `padrao_documento`.`T_TIPO_OBJT` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `padrao_documento`.`T_TIPO_OBJT` (
  `ID_TIPO_OBJT` INT NOT NULL COMMENT 'Identificador único do tipo do objeto',
  `DS_TIPO_OBJT` VARCHAR(45) NOT NULL COMMENT 'Descricao do tipo de objeto',
  PRIMARY KEY (`ID_TIPO_OBJT`));
ENGINE = InnoDB;

SHOW WARNINGS;


-- -----------------------------------------------------
--
-- -----------------------------------------------------
ALTER TABLE Persons
ADD CONSTRAINT PK_Person PRIMARY KEY (ID,LastName);

ALTER TABLE employees
ADD last_name VARCHAR(50),
	first_name VARCHAR(40);
	  
ALTER TABLE one
ADD two_id INTEGER,
ADD CONSTRAINT FK_Teste FOREIGN KEY(two_id) REFERENCES two(id);

-- -----------------------------------------------------
-- Table `padrao_documento`.`T_SPDC_OBJT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `padrao_documento`.`T_SPDC_OBJT` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `padrao_documento`.`T_SPDC_OBJT` (
  `ID_OBJT` INT NOT NULL COMMENT 'Identificador único do objeto inserido no sistema de padronizao de documentos.',
  `ID_TIPO_OBJT` INT NOT NULL,
  `ID_PRFX` INT NOT NULL COMMENT 'Identificador único do prefixo que compoe o nome do objeto',
  `NM_OBJT` VARCHAR(50) NOT NULL COMMENT 'Nome do objeto de padronizacao de documentos.',
  `DC_OBJT` VARCHAR(1000) NULL COMMENT 'Descricao a respeito do objeto.',
  PRIMARY KEY (`ID_OBJT`),
  CONSTRAINT `fk_tipo_objt_01`
    FOREIGN KEY (`ID_TIPO_OBJT`)
    REFERENCES `padrao_documento`.`T_TIPO_OBJT` (`ID_TIPO_OBJT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prfx_objt_02`
    FOREIGN KEY (`ID_PRFX`)
    REFERENCES `padrao_documento`.`T_SPDC_PRFX` (`ID_PRFX`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `IX_SPDC_OBJT01` ON `padrao_documento`.`T_SPDC_OBJT` (`ID_TIPO_OBJT` ASC);

SHOW WARNINGS;
CREATE INDEX `FK_PRFX_OBJT_01` ON `padrao_documento`.`T_SPDC_OBJT` (`ID_PRFX` ASC);

SHOW WARNINGS;

SHOW WARNINGS;
CREATE INDEX `IX_SPDC_VOCB_CNTLD` ON `padrao_documento`.`T_SPDC_OBJT_VOCB_CNTLD` (`ID_VOCB_CNTLD` ASC);

SHOW WARNINGS;
CREATE INDEX `IX_SPDC_OBJT_VOCB_CNTLD` ON `padrao_documento`.`T_SPDC_OBJT_VOCB_CNTLD` (`ID_OBJT` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `padrao_documento`.`T_SPDC_PRPD_OBJT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `padrao_documento`.`T_SPDC_PRPD_OBJT` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `padrao_documento`.`TB_SPDC_PRPD_OBJT` (
  `ID_PRPDYY_OBJT` INT NOT NULL COMMENT 'Identificador unico das propriedades de um objeto.',
  `ID_PRFX` INT NOT NULL COMMENT 'Identificador unico do prefixo de objetos do banco. Por exemplo DS para atributos usados como descricao e T para tabelas.',
  `ID_OBJT` INT NOT NULL COMMENT 'Identificador único do objeto inserido no sistema de padronizao de documentos.',
  `NM_PRPD_OBJT` VARCHAR(50) NOT NULL,
  `DC_PRPD_OBJT` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`ID_PRPD_OBJT`),
  CONSTRAINT `FK_OBJT_PRPD_01`
    FOREIGN KEY (`ID_OBJT`)
    REFERENCES `padrao_documento`.`T_SPDC_OBJT` (`ID_OBJT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRFX_PRPD_OBJT_02`
    FOREIGN KEY (`ID_PRFX`)
    REFERENCES `padrao_documento`.`T_SPDC_PRFX` (`ID_PRFX`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `IX_SPDC_OBJT_PRPD1` ON `padrao_documento`.`T_SPDC_PRPD_OBJT` (`ID_OBJT` ASC);

SHOW WARNINGS;
CREATE INDEX `IX_SPDC_OBJT_PRPD2` ON `padrao_documento`.`T_SPDC_PRPD_OBJT` (`ID_PRFX` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `padrao_documento`.`T_SPDC_PRPD_VOCB_CNTLD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `padrao_documento`.`T_SPDC_PRPD_VOCB_CNTLD` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `padrao_documento`.`T_SPDC_PRPD_VOCB_CNTLD` (
  `ID_PRPD_OBJT` INT NOT NULL COMMENT 'Identificador unico das propriedades de um objeto.',
  `ID_VOCB_CNTLD` INT NOT NULL COMMENT 'Identificador unico da tabela de vocabularios controlados.',
  PRIMARY KEY (`ID_PRPD_OBJT`, `ID_VOCB_CNTLD`),
  CONSTRAINT `FK_SPDC_PRPD_VOCB_CNTLD01`
    FOREIGN KEY (`ID_VOCB_CNTLD`)
    REFERENCES `padrao_documento`.`T_SPDC_VOCB_CNTLD` (`ID_VOCB_CNTLD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_SPDC_PRPD_VOCB_CNTLD02`
    FOREIGN KEY (`ID_PRPD_OBJT`)
    REFERENCES `padrao_documento`.`T_SPDC_PRPD_OBJT` (`ID_PRPD_OBJT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `IX_SPDC_PRPD_VOCB_CNTLD` ON `padrao_documento`.`T_SPDC_PRPD_VOCB_CNTLD` (`ID_VOCB_CNTLD` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `padrao_documento`.`T_SPDC_PRMT_ACSSO_TXTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `padrao_documento`.`T_SPDC_PRMT_ACSSO_TXTO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `padrao_documento`.`T_SPDC_PRMT_ACSSO_TXTO` (
  `ID_PRMT_ACSSO_TXTO` INT NOT NULL,
  `DS_PRMT_ACSSO_TXTO` VARCHAR(100) NULL COMMENT 'Descricao do parametro de acesso a texto. Por exemplo, PUBLIC CLASS, CREATE TABLE.',
  `NU_INIC_ACSSO_TXTO` VARCHAR(10) NULL COMMENT 'Numero do inicio de acesso ao texto lido.',
  `NU_FIM_ACSSO_TXTO` VARCHAR(10) NULL COMMENT 'Numero do fim de acesso ao texto lido.',
  `FL_INIC_ACSSO_TXTO` VARCHAR(5) NULL COMMENT 'Flag de inicio de leitura do acesso ao texto a ser reconhecido na leitura de um documento a ser verificado de acordo com os padrÃµes.',
  `FL_FIM_ACSSO_TXTO` VARCHAR(5) NULL COMMENT 'Flag de fim de leitura do acesso ao texto a ser reconhecido na leitura de um documento a ser verificado de acordo com os padrÃµes.',
  `IC_TIPO_ACSSO_TXTO` VARCHAR(100) NULL COMMENT 'Indicador do tipo do texto a ser ',
  PRIMARY KEY (`ID_PRMT_ACSSO_TXTO`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


